UsingAbility: true
UsingChanging: true
UsingMission: true

GameWorld:
  Size_Pos1: 0
  Size_Pos2: 0
  StartLocations: []
  MissionLocations: []
  MissionAssignLocations: []

SpawnBlock: 0
MissionAssignBlock: 0