name: ChangedChaser
version: 1.0
author: minshigee
main: com.minshigee.changedchaser.ChangedChaser
api-version: 1.16
commands:
    ph:
        description: Changed Chaser commands
        usage: /<command>