name: ChangedChaser
version: 1.0
author: minshigee
main: com.minshigee.playerchanger.PlayerChanger
api-version: 1.16
commands:
    ph:
        description: Player Changer commands
        usage: /<command>