UsingAbility: true
UsingMission: true
GameWorld:
  Size_Pos1:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    pitch: 90.0
    yaw: 38.099976
  Size_Pos2:
    ==: org.bukkit.Location
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    pitch: 90.0
    yaw: 38.39998
